# Generated by Django 5.0 on 2023-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appturnos', '0002_reserva_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_evento',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
